name: example-environment
dependencies:
  - numpy
  - matplotlib
  - pandas
  - xarray
  - netCDF4
  - Basemap
  - Path
  - matplotlib.patches
  - pip:
    - datetime
    - timedelta
    - copy
    - matplotlib.patches
